version: "3.1"

services:

    db:
        image: mysql:8
        ports:
          - 3306:3306
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: espocrmdb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql --user 1000

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8000:80            
        restart: always
        depends_on:
          - db
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: password

    espocrmweb:
        build: .
        ports:
          - 8080:80
        restart: always
        depends_on:
          - db
        volumes:
            - espocrm-data:/var/www/html --user 1000

volumes:
  mysql:
  espocrm-data:
